using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExcelOperations.Migrations
{
    /// <inheritdoc />
    public partial class MigrationV1 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "RouterAktuell",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    ZustandigeRegion = table.Column<string>(type: "text", nullable: true),
                    SONumber = table.Column<string>(type: "text", nullable: true),
                    SONrEPlus = table.Column<string>(name: "SO_Nr_EPlus", type: "text", nullable: true),
                    PLZ = table.Column<string>(type: "text", nullable: true),
                    Ort = table.Column<string>(type: "text", nullable: true),
                    Strasse = table.Column<string>(type: "text", nullable: true),
                    Gebaudeart = table.Column<string>(type: "text", nullable: true),
                    Eigentumer = table.Column<string>(type: "text", nullable: true),
                    CtKStatus = table.Column<string>(name: "CtK_Status", type: "text", nullable: true),
                    NENr = table.Column<string>(name: "NE_Nr", type: "text", nullable: true),
                    Alt = table.Column<string>(type: "text", nullable: true),
                    DimOSPF = table.Column<string>(name: "Dim_OSPF", type: "text", nullable: true),
                    NEName = table.Column<string>(name: "NE_Name", type: "text", nullable: true),
                    NEBemerkung = table.Column<string>(name: "NE_Bemerkung", type: "text", nullable: true),
                    NENrEPlus = table.Column<string>(name: "NE_Nr_EPlus", type: "text", nullable: true),
                    Projektstand = table.Column<string>(type: "text", nullable: true),
                    Projektart = table.Column<string>(type: "text", nullable: true),
                    DimSquads = table.Column<string>(name: "Dim_Squads", type: "text", nullable: true),
                    SWDPOCSourcing = table.Column<string>(name: "SWD_POC_Sourcing", type: "text", nullable: true),
                    NRGTransition = table.Column<string>(name: "NRG_Transition", type: "text", nullable: true),
                    TemplateBezeichnung = table.Column<string>(name: "Template_Bezeichnung", type: "text", nullable: true),
                    Projektbemerkung = table.Column<string>(type: "text", nullable: true),
                    ProjektID = table.Column<string>(name: "Projekt_ID", type: "text", nullable: true),
                    MPPOC = table.Column<string>(name: "MP_POC", type: "text", nullable: true),
                    Bezeichnung = table.Column<string>(type: "text", nullable: true),
                    VerantwOrganisationseinheit = table.Column<string>(name: "Verantw_Organisationseinheit", type: "text", nullable: true),
                    InfrastrukturSollBaseframeRadioMW = table.Column<string>(name: "Infrastruktur_Soll_Baseframe_Radio_MW", type: "text", nullable: true),
                    ZieldesProjekts = table.Column<string>(name: "Ziel_des_Projekts", type: "text", nullable: true),
                    POCProjekt = table.Column<string>(name: "POC_Projekt", type: "text", nullable: true),
                    DimPOCProjekt = table.Column<string>(name: "Dim_POC_Projekt", type: "text", nullable: true),
                    Demand = table.Column<string>(type: "text", nullable: true),
                    DimBeauftragungsform = table.Column<string>(name: "Dim_Beauftragungsform", type: "text", nullable: true),
                    ProjektEquipment = table.Column<string>(name: "Projekt_Equipment", type: "text", nullable: true),
                    KolNE78MxMS = table.Column<string>(name: "Kol_NE78_MxMS", type: "text", nullable: true),
                    Festnetzplaner = table.Column<string>(type: "text", nullable: true),
                    GUTransport = table.Column<string>(name: "GU_Transport", type: "text", nullable: true),
                    GUProjekt = table.Column<string>(name: "GU_Projekt", type: "text", nullable: true),
                    AnzNE30 = table.Column<string>(name: "Anz_NE30", type: "text", nullable: true),
                    AnzNE31 = table.Column<string>(name: "Anz_NE31", type: "text", nullable: true),
                    AnzNE32 = table.Column<string>(name: "Anz_NE32", type: "text", nullable: true),
                    AnzNE33 = table.Column<string>(name: "Anz_NE33", type: "text", nullable: true),
                    IstStx11 = table.Column<string>(name: "Ist_Stx11", type: "text", nullable: true),
                    Stx11Bemerkung = table.Column<string>(name: "Stx11_Bemerkung", type: "text", nullable: true),
                    IstStx18b = table.Column<string>(name: "Ist_Stx18b", type: "text", nullable: true),
                    IstStx29b = table.Column<string>(name: "Ist_Stx29b", type: "text", nullable: true),
                    IstStx29t = table.Column<string>(name: "Ist_Stx29t", type: "text", nullable: true),
                    Stx29tBemerkung = table.Column<string>(name: "Stx29t_Bemerkung", type: "text", nullable: true),
                    IstStx29y = table.Column<string>(name: "Ist_Stx29y", type: "text", nullable: true),
                    IstStx29z = table.Column<string>(name: "Ist_Stx29z", type: "text", nullable: true),
                    Stx29zBemerkung = table.Column<string>(name: "Stx29z_Bemerkung", type: "text", nullable: true),
                    IstStx30 = table.Column<string>(name: "Ist_Stx30", type: "text", nullable: true),
                    Stx30Bemerkung = table.Column<string>(name: "Stx30_Bemerkung", type: "text", nullable: true),
                    IstStx43a = table.Column<string>(name: "Ist_Stx43a", type: "text", nullable: true),
                    Stx43aBemerkung = table.Column<string>(name: "Stx43a_Bemerkung", type: "text", nullable: true),
                    TOMPLANNINGPREPARATION = table.Column<string>(name: "TOM_PLANNING_PREPARATION", type: "text", nullable: true),
                    IstStx43c = table.Column<string>(name: "Ist_Stx43c", type: "text", nullable: true),
                    IstStx43 = table.Column<string>(name: "Ist_Stx43", type: "text", nullable: true),
                    IstStx44 = table.Column<string>(name: "Ist_Stx44", type: "text", nullable: true),
                    Stx44Bemerkung = table.Column<string>(name: "Stx44_Bemerkung", type: "text", nullable: true),
                    PlanStx40 = table.Column<string>(name: "Plan_Stx40", type: "text", nullable: true),
                    IstStx40 = table.Column<string>(name: "Ist_Stx40", type: "text", nullable: true),
                    Stx40Bemerkung = table.Column<string>(name: "Stx40_Bemerkung", type: "text", nullable: true),
                    IstStx40Stern = table.Column<string>(name: "Ist_Stx40Stern", type: "text", nullable: true),
                    IstStx53 = table.Column<string>(name: "Ist_Stx53", type: "text", nullable: true),
                    Stx53Bemerkung = table.Column<string>(name: "Stx53_Bemerkung", type: "text", nullable: true),
                    SollStx62j = table.Column<string>(name: "Soll_Stx62j", type: "text", nullable: true),
                    PlanStx62j = table.Column<string>(name: "Plan_Stx62j", type: "text", nullable: true),
                    IstStx62j = table.Column<string>(name: "Ist_Stx62j", type: "text", nullable: true),
                    Stx62jBemerkung = table.Column<string>(name: "Stx62j_Bemerkung", type: "text", nullable: true),
                    IstStx62w = table.Column<string>(name: "Ist_Stx62w", type: "text", nullable: true),
                    Stx62wBemerkung = table.Column<string>(name: "Stx62w_Bemerkung", type: "text", nullable: true),
                    IstStx62r = table.Column<string>(name: "Ist_Stx62r", type: "text", nullable: true),
                    IstStx52b = table.Column<string>(name: "Ist_Stx52b", type: "text", nullable: true),
                    Stx52bBemerkung = table.Column<string>(name: "Stx52b_Bemerkung", type: "text", nullable: true),
                    PlanStx59 = table.Column<string>(name: "Plan_Stx59", type: "text", nullable: true),
                    IstStx59 = table.Column<string>(name: "Ist_Stx59", type: "text", nullable: true),
                    Stx59Bemerkung = table.Column<string>(name: "Stx59_Bemerkung", type: "text", nullable: true),
                    PlanStx59k = table.Column<string>(name: "Plan_Stx59k", type: "text", nullable: true),
                    IstStx59k = table.Column<string>(name: "Ist_Stx59k", type: "text", nullable: true),
                    Stx59kBemerkung = table.Column<string>(name: "Stx59k_Bemerkung", type: "text", nullable: true),
                    TOMEXECUTION = table.Column<string>(name: "TOM_EXECUTION", type: "text", nullable: true),
                    IstStx60 = table.Column<string>(name: "Ist_Stx60", type: "text", nullable: true),
                    Stx60Bemerkung = table.Column<string>(name: "Stx60_Bemerkung", type: "text", nullable: true),
                    IstStx62a = table.Column<string>(name: "Ist_Stx62a", type: "text", nullable: true),
                    Stx62aBemerkung = table.Column<string>(name: "Stx62a_Bemerkung", type: "text", nullable: true),
                    PlanStx62g = table.Column<string>(name: "Plan_Stx62g", type: "text", nullable: true),
                    IstStx62g = table.Column<string>(name: "Ist_Stx62g", type: "text", nullable: true),
                    Stx62gBemerkung = table.Column<string>(name: "Stx62g_Bemerkung", type: "text", nullable: true),
                    IstStx51a = table.Column<string>(name: "Ist_Stx51a", type: "text", nullable: true),
                    IstStx51b = table.Column<string>(name: "Ist_Stx51b", type: "text", nullable: true),
                    Stx51bBemerkung = table.Column<string>(name: "Stx51b_Bemerkung", type: "text", nullable: true),
                    IstStx51r = table.Column<string>(name: "Ist_Stx51r", type: "text", nullable: true),
                    Stx51rBemerkung = table.Column<string>(name: "Stx51r_Bemerkung", type: "text", nullable: true),
                    SollStx71 = table.Column<string>(name: "Soll_Stx71", type: "text", nullable: true),
                    PlanStx71 = table.Column<string>(name: "Plan_Stx71", type: "text", nullable: true),
                    IstStx71 = table.Column<string>(name: "Ist_Stx71", type: "text", nullable: true),
                    Stx71Bemerkung = table.Column<string>(name: "Stx71_Bemerkung", type: "text", nullable: true),
                    IstStx71a = table.Column<string>(name: "Ist_Stx71a", type: "text", nullable: true),
                    IstStx71b = table.Column<string>(name: "Ist_Stx71b", type: "text", nullable: true),
                    Stx71bBemerkung = table.Column<string>(name: "Stx71b_Bemerkung", type: "text", nullable: true),
                    IstStx71c = table.Column<string>(name: "Ist_Stx71c", type: "text", nullable: true),
                    Stx71cBemerkung = table.Column<string>(name: "Stx71c_Bemerkung", type: "text", nullable: true),
                    IstStx80 = table.Column<string>(name: "Ist_Stx80", type: "text", nullable: true),
                    Stx80Bemerkung = table.Column<string>(name: "Stx80_Bemerkung", type: "text", nullable: true),
                    PlanStx88i = table.Column<string>(name: "Plan_Stx88i", type: "text", nullable: true),
                    IstStx88i = table.Column<string>(name: "Ist_Stx88i", type: "text", nullable: true),
                    Stx88iBemerkung = table.Column<string>(name: "Stx88i_Bemerkung", type: "text", nullable: true),
                    IstStx87r = table.Column<string>(name: "Ist_Stx87r", type: "text", nullable: true),
                    IstStx89 = table.Column<string>(name: "Ist_Stx89", type: "text", nullable: true),
                    SollStx90 = table.Column<string>(name: "Soll_Stx90", type: "text", nullable: true),
                    PlanStx90 = table.Column<string>(name: "Plan_Stx90", type: "text", nullable: true),
                    IstStx90 = table.Column<string>(name: "Ist_Stx90", type: "text", nullable: true),
                    Stx90Bemerkung = table.Column<string>(name: "Stx90_Bemerkung", type: "text", nullable: true),
                    PlanStx91 = table.Column<string>(name: "Plan_Stx91", type: "text", nullable: true),
                    IstStx91 = table.Column<string>(name: "Ist_Stx91", type: "text", nullable: true),
                    Stx91Bemerkung = table.Column<string>(name: "Stx91_Bemerkung", type: "text", nullable: true),
                    IstStx91c = table.Column<string>(name: "Ist_Stx91c", type: "text", nullable: true),
                    IstStx91r = table.Column<string>(name: "Ist_Stx91r", type: "text", nullable: true),
                    UTSTicketamProjekt = table.Column<string>(name: "UTS_Ticket_am_Projekt", type: "text", nullable: true),
                    IstStx30n = table.Column<string>(name: "Ist_Stx30n", type: "text", nullable: true),
                    Stx30nBemerkung = table.Column<string>(name: "Stx30n_Bemerkung", type: "text", nullable: true),
                    IstStx52n = table.Column<string>(name: "Ist_Stx52n", type: "text", nullable: true),
                    Stx52nBemerkung = table.Column<string>(name: "Stx52n_Bemerkung", type: "text", nullable: true),
                    PlanStx68n = table.Column<string>(name: "Plan_Stx68n", type: "text", nullable: true),
                    IstStx68n = table.Column<string>(name: "Ist_Stx68n", type: "text", nullable: true),
                    Stx68nBemerkung = table.Column<string>(name: "Stx68n_Bemerkung", type: "text", nullable: true),
                    IstStx30o = table.Column<string>(name: "Ist_Stx30o", type: "text", nullable: true),
                    IstStx68o = table.Column<string>(name: "Ist_Stx68o", type: "text", nullable: true),
                    IstStx30p = table.Column<string>(name: "Ist_Stx30p", type: "text", nullable: true),
                    Stx30pBemerkung = table.Column<string>(name: "Stx30p_Bemerkung", type: "text", nullable: true),
                    IstStx52p = table.Column<string>(name: "Ist_Stx52p", type: "text", nullable: true),
                    Stx52pBemerkung = table.Column<string>(name: "Stx52p_Bemerkung", type: "text", nullable: true),
                    PlanStx68p = table.Column<string>(name: "Plan_Stx68p", type: "text", nullable: true),
                    IstStx68p = table.Column<string>(name: "Ist_Stx68p", type: "text", nullable: true),
                    Stx68pBemerkung = table.Column<string>(name: "Stx68p_Bemerkung", type: "text", nullable: true),
                    LLIst = table.Column<string>(name: "LL_Ist", type: "text", nullable: true),
                    DFIst = table.Column<string>(name: "DF_Ist", type: "text", nullable: true),
                    MWIst = table.Column<string>(name: "MW_Ist", type: "text", nullable: true),
                    WLIst = table.Column<string>(name: "WL_Ist", type: "text", nullable: true),
                    SATIst = table.Column<string>(name: "SAT_Ist", type: "text", nullable: true),
                    LL = table.Column<string>(type: "text", nullable: true),
                    DF = table.Column<string>(type: "text", nullable: true),
                    MW = table.Column<string>(type: "text", nullable: true),
                    WL = table.Column<string>(type: "text", nullable: true),
                    SAT = table.Column<string>(type: "text", nullable: true),
                    LL1stStx90 = table.Column<string>(name: "LL_1st_Stx90", type: "text", nullable: true),
                    DF1stStx90 = table.Column<string>(name: "DF_1st_Stx90", type: "text", nullable: true),
                    MW1stStx90 = table.Column<string>(name: "MW_1st_Stx90", type: "text", nullable: true),
                    WL1stStx90 = table.Column<string>(name: "WL_1st_Stx90", type: "text", nullable: true),
                    SAT1stStx90 = table.Column<string>(name: "SAT_1st_Stx90", type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RouterAktuell", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "RouterSwapAktuells",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    ZuständigeRegion = table.Column<string>(type: "text", nullable: true),
                    SONr = table.Column<string>(name: "SO_Nr", type: "text", nullable: true),
                    DimSquadsMAC = table.Column<string>(name: "Dim_SquadsMAC", type: "text", nullable: true),
                    SONrEPlus = table.Column<string>(name: "SO_Nr_EPlus", type: "text", nullable: true),
                    PLZ = table.Column<string>(type: "text", nullable: true),
                    Ort = table.Column<string>(type: "text", nullable: true),
                    Strabe = table.Column<string>(type: "text", nullable: true),
                    Gebaudeart = table.Column<string>(type: "text", nullable: true),
                    Eigentumer = table.Column<string>(type: "text", nullable: true),
                    StandortKlasse = table.Column<string>(type: "text", nullable: true),
                    POCBEnde = table.Column<string>(type: "text", nullable: true),
                    NENr = table.Column<string>(name: "NE_Nr", type: "text", nullable: true),
                    Alt = table.Column<string>(type: "text", nullable: true),
                    ProjektID = table.Column<string>(type: "text", nullable: true),
                    Routeralt = table.Column<string>(type: "text", nullable: true),
                    Routerneu = table.Column<string>(type: "text", nullable: true),
                    aktuell = table.Column<string>(type: "text", nullable: true),
                    VerbindlicherJSLRouter = table.Column<string>(type: "text", nullable: true),
                    LindaGrundgerat = table.Column<string>(name: "Linda_Grundgerat", type: "text", nullable: true),
                    LindaStatusLeitung = table.Column<string>(name: "Linda_StatusLeitung", type: "text", nullable: true),
                    NEName = table.Column<string>(name: "NE_Name", type: "text", nullable: true),
                    NEBemerkung = table.Column<string>(name: "NE_Bemerkung", type: "text", nullable: true),
                    dimOSPFRulexakta = table.Column<string>(name: "dim_OSPFRulexakta", type: "text", nullable: true),
                    Projektstand = table.Column<string>(type: "text", nullable: true),
                    geplantesEnde = table.Column<string>(type: "text", nullable: true),
                    Projektbemerkung = table.Column<string>(type: "text", nullable: true),
                    Demand = table.Column<string>(type: "text", nullable: true),
                    DimBeauftragungsform = table.Column<string>(name: "Dim_Beauftragungsform", type: "text", nullable: true),
                    Projektart = table.Column<string>(type: "text", nullable: true),
                    TemplateBezeichnung = table.Column<string>(type: "text", nullable: true),
                    MPPOC = table.Column<string>(name: "MP_POC", type: "text", nullable: true),
                    UGG = table.Column<string>(type: "text", nullable: true),
                    Bezeichnung = table.Column<string>(type: "text", nullable: true),
                    VerantwOrgeinheit = table.Column<string>(type: "text", nullable: true),
                    POCProjekt = table.Column<string>(type: "text", nullable: true),
                    AnzNE20 = table.Column<string>(name: "Anz_NE20", type: "text", nullable: true),
                    AnzNE21 = table.Column<string>(name: "Anz_NE21", type: "text", nullable: true),
                    AnzNE30 = table.Column<string>(name: "Anz_NE30", type: "text", nullable: true),
                    AnzNE31 = table.Column<string>(name: "Anz_NE31", type: "text", nullable: true),
                    AnzNE32 = table.Column<string>(name: "Anz_NE32", type: "text", nullable: true),
                    AnzNE33 = table.Column<string>(name: "Anz_NE33", type: "text", nullable: true),
                    IMID = table.Column<string>(name: "IM_ID", type: "text", nullable: true),
                    IMStatus = table.Column<string>(name: "IM_Status", type: "text", nullable: true),
                    IMgeplInstallation = table.Column<string>(name: "IM_gepl_Installation", type: "text", nullable: true),
                    IMgeplLieferung = table.Column<string>(name: "IM_gepl_Lieferung", type: "text", nullable: true),
                    DIMID = table.Column<string>(name: "DIM_ID", type: "text", nullable: true),
                    DIMStatus = table.Column<string>(name: "DIM_Status", type: "text", nullable: true),
                    DIMzustAbbauer = table.Column<string>(name: "DIM_zust_Abbauer", type: "text", nullable: true),
                    Festnetzplaner = table.Column<string>(type: "text", nullable: true),
                    GUProjekt = table.Column<string>(name: "GU_Projekt", type: "text", nullable: true),
                    AuftragnehmerSystemtechnik = table.Column<string>(type: "text", nullable: true),
                    IstStx11 = table.Column<string>(name: "Ist_Stx11", type: "text", nullable: true),
                    Stx11Bemerkung = table.Column<string>(name: "Stx11_Bemerkung", type: "text", nullable: true),
                    PlanStx29z = table.Column<string>(name: "Plan_Stx29z", type: "text", nullable: true),
                    IstStx29z = table.Column<string>(name: "Ist_Stx29z", type: "text", nullable: true),
                    Stx29zBemerkung = table.Column<string>(name: "Stx29z_Bemerkung", type: "text", nullable: true),
                    IstStx30 = table.Column<string>(name: "Ist_Stx30", type: "text", nullable: true),
                    Stx30Bemerkung = table.Column<string>(name: "Stx30_Bemerkung", type: "text", nullable: true),
                    IstStx43a = table.Column<string>(name: "Ist_Stx43a", type: "text", nullable: true),
                    Stx43aBemerkung = table.Column<string>(name: "Stx43a_Bemerkung", type: "text", nullable: true),
                    TOMPLANNINGPREPARATION = table.Column<string>(name: "TOM_PLANNING_PREPARATION", type: "text", nullable: true),
                    IstStx44 = table.Column<string>(name: "Ist_Stx44", type: "text", nullable: true),
                    Stx44Bemerkung = table.Column<string>(name: "Stx44_Bemerkung", type: "text", nullable: true),
                    PlanStx62j = table.Column<string>(name: "Plan_Stx62j", type: "text", nullable: true),
                    IstStx62j = table.Column<string>(name: "Ist_Stx62j", type: "text", nullable: true),
                    Stx62jBemerkung = table.Column<string>(name: "Stx62j_Bemerkung", type: "text", nullable: true),
                    IstStx62w = table.Column<string>(name: "Ist_Stx62w", type: "text", nullable: true),
                    Stx62wBemerkung = table.Column<string>(name: "Stx62w_Bemerkung", type: "text", nullable: true),
                    IstStx62r = table.Column<string>(name: "Ist_Stx62r", type: "text", nullable: true),
                    PlanStx59 = table.Column<string>(name: "Plan_Stx59", type: "text", nullable: true),
                    IstStx59 = table.Column<string>(name: "Ist_Stx59", type: "text", nullable: true),
                    Stx59Bemerkung = table.Column<string>(name: "Stx59_Bemerkung", type: "text", nullable: true),
                    PlanStx59k = table.Column<string>(name: "Plan_Stx59k", type: "text", nullable: true),
                    IstStx59k = table.Column<string>(name: "Ist_Stx59k", type: "text", nullable: true),
                    Stx59kBemerkung = table.Column<string>(name: "Stx59k_Bemerkung", type: "text", nullable: true),
                    TOMEXECUTION = table.Column<string>(name: "TOM_EXECUTION", type: "text", nullable: true),
                    IstStx60 = table.Column<string>(name: "Ist_Stx60", type: "text", nullable: true),
                    Stx60Bemerkung = table.Column<string>(name: "Stx60_Bemerkung", type: "text", nullable: true),
                    IstStx62a = table.Column<string>(name: "Ist_Stx62a", type: "text", nullable: true),
                    Stx62aBemerkung = table.Column<string>(name: "Stx62a_Bemerkung", type: "text", nullable: true),
                    PlanStx62g = table.Column<string>(name: "Plan_Stx62g", type: "text", nullable: true),
                    IstStx62g = table.Column<string>(name: "Ist_Stx62g", type: "text", nullable: true),
                    Stx62gBemerkung = table.Column<string>(name: "Stx62g_Bemerkung", type: "text", nullable: true),
                    SollStx48 = table.Column<string>(name: "Soll_Stx48", type: "text", nullable: true),
                    PlanStx48 = table.Column<string>(name: "Plan_Stx48", type: "text", nullable: true),
                    IstStx48 = table.Column<string>(name: "Ist_Stx48", type: "text", nullable: true),
                    IstStx50 = table.Column<string>(name: "Ist_Stx50", type: "text", nullable: true),
                    SollStx51a = table.Column<string>(name: "Soll_Stx51a", type: "text", nullable: true),
                    PlanStx51a = table.Column<string>(name: "Plan_Stx51a", type: "text", nullable: true),
                    IstStx51a = table.Column<string>(name: "Ist_Stx51a", type: "text", nullable: true),
                    Stx51aBemerkung = table.Column<string>(name: "Stx51a_Bemerkung", type: "text", nullable: true),
                    IstStx51b = table.Column<string>(name: "Ist_Stx51b", type: "text", nullable: true),
                    Stx51bBemerkung = table.Column<string>(name: "Stx51b_Bemerkung", type: "text", nullable: true),
                    IstStx51r = table.Column<string>(name: "Ist_Stx51r", type: "text", nullable: true),
                    Stx51rBemerkung = table.Column<string>(name: "Stx51r_Bemerkung", type: "text", nullable: true),
                    IstStx70 = table.Column<string>(name: "Ist_Stx70", type: "text", nullable: true),
                    SollStx71 = table.Column<string>(name: "Soll_Stx71", type: "text", nullable: true),
                    PlanStx71 = table.Column<string>(name: "Plan_Stx71", type: "text", nullable: true),
                    IstStx71 = table.Column<string>(name: "Ist_Stx71", type: "text", nullable: true),
                    Stx71Bemerkung = table.Column<string>(name: "Stx71_Bemerkung", type: "text", nullable: true),
                    IstStx71a = table.Column<string>(name: "Ist_Stx71a", type: "text", nullable: true),
                    Stx71aBemerkung = table.Column<string>(name: "Stx71a_Bemerkung", type: "text", nullable: true),
                    IstStx71b = table.Column<string>(name: "Ist_Stx71b", type: "text", nullable: true),
                    Stx71bBemerkung = table.Column<string>(name: "Stx71b_Bemerkung", type: "text", nullable: true),
                    IstStx71c = table.Column<string>(name: "Ist_Stx71c", type: "text", nullable: true),
                    Stx71cBemerkung = table.Column<string>(name: "Stx71c_Bemerkung", type: "text", nullable: true),
                    IstStx88i = table.Column<string>(name: "Ist_Stx88i", type: "text", nullable: true),
                    Stx88iBemerkung = table.Column<string>(name: "Stx88i_Bemerkung", type: "text", nullable: true),
                    PlanStx90 = table.Column<string>(name: "Plan_Stx90", type: "text", nullable: true),
                    IstStx90 = table.Column<string>(name: "Ist_Stx90", type: "text", nullable: true),
                    Stx90Bemerkung = table.Column<string>(name: "Stx90_Bemerkung", type: "text", nullable: true),
                    PlanStx91 = table.Column<string>(name: "Plan_Stx91", type: "text", nullable: true),
                    IstStx91 = table.Column<string>(name: "Ist_Stx91", type: "text", nullable: true),
                    Stx91Bemerkung = table.Column<string>(name: "Stx91_Bemerkung", type: "text", nullable: true),
                    PlanStx91a = table.Column<string>(name: "Plan_Stx91a", type: "text", nullable: true),
                    IstStx91a = table.Column<string>(name: "Ist_Stx91a", type: "text", nullable: true),
                    Stx91aBemerkung = table.Column<string>(name: "Stx91a_Bemerkung", type: "text", nullable: true),
                    IstStx91c = table.Column<string>(name: "Ist_Stx91c", type: "text", nullable: true),
                    IstStx91r = table.Column<string>(name: "Ist_Stx91r", type: "text", nullable: true),
                    IstStx30n = table.Column<string>(name: "Ist_Stx30n", type: "text", nullable: true),
                    PlanStx68n = table.Column<string>(name: "Plan_Stx68n", type: "text", nullable: true),
                    IstStx68n = table.Column<string>(name: "Ist_Stx68n", type: "text", nullable: true),
                    Stx68nBemerkung = table.Column<string>(name: "Stx68n_Bemerkung", type: "text", nullable: true),
                    RLM = table.Column<string>(type: "text", nullable: true),
                    CRQGU = table.Column<string>(name: "CRQ_GU", type: "text", nullable: true),
                    LLIst = table.Column<string>(name: "LL_Ist", type: "text", nullable: true),
                    DFIst = table.Column<string>(name: "DF_Ist", type: "text", nullable: true),
                    RSTPIst = table.Column<string>(name: "RSTP_Ist", type: "text", nullable: true),
                    MWIst = table.Column<string>(name: "MW_Ist", type: "text", nullable: true),
                    SollWL = table.Column<string>(name: "Soll_WL", type: "text", nullable: true),
                    FNEProjektart = table.Column<string>(name: "FNE_Projektart", type: "text", nullable: true),
                    FNENENr = table.Column<string>(name: "FNE_NE_Nr", type: "text", nullable: true),
                    FNEAlt = table.Column<string>(name: "FNE_Alt", type: "text", nullable: true),
                    FNEProjektID = table.Column<string>(name: "FNE_ProjektID", type: "text", nullable: true),
                    FNEProjektstand = table.Column<string>(name: "FNE_Projektstand", type: "text", nullable: true),
                    FNEProjektbemerkung = table.Column<string>(name: "FNE_Projektbemerkung", type: "text", nullable: true),
                    FNEGUProjekt = table.Column<string>(name: "FNE_GU_Projekt", type: "text", nullable: true),
                    FNEDemand = table.Column<string>(name: "FNE_Demand", type: "text", nullable: true),
                    FNETemplateBezeichnung = table.Column<string>(name: "FNE_TemplateBezeichnung", type: "text", nullable: true),
                    FNEMPPOC = table.Column<string>(name: "FNE_MP_POC", type: "text", nullable: true),
                    FNEProjektbezeichnung = table.Column<string>(name: "FNE_Projektbezeichnung", type: "text", nullable: true),
                    FNEVerantwOrg = table.Column<string>(name: "FNE_VerantwOrg", type: "text", nullable: true),
                    FNEPOCProjekt = table.Column<string>(name: "FNE_POCProjekt", type: "text", nullable: true),
                    FNEIstStx30 = table.Column<string>(name: "FNE_Ist_Stx30", type: "text", nullable: true),
                    FNEStx30Bemerkung = table.Column<string>(name: "FNE_Stx30_Bemerkung", type: "text", nullable: true),
                    FNEPlanStx40Stern = table.Column<string>(name: "FNE_Plan_Stx40Stern", type: "text", nullable: true),
                    FNEIstStx40Stern = table.Column<string>(name: "FNE_Ist_Stx40Stern", type: "text", nullable: true),
                    FNEStx40SternBemerkung = table.Column<string>(name: "FNE_Stx40Stern_Bemerkung", type: "text", nullable: true),
                    FNEIstStx43a = table.Column<string>(name: "FNE_Ist_Stx43a", type: "text", nullable: true),
                    FNEStx43aBemerkung = table.Column<string>(name: "FNE_Stx43a_Bemerkung", type: "text", nullable: true),
                    FNEIstStx44 = table.Column<string>(name: "FNE_Ist_Stx44", type: "text", nullable: true),
                    FNEStx44Bemerkung = table.Column<string>(name: "FNE_Stx44_Bemerkung", type: "text", nullable: true),
                    FNEIstStx52 = table.Column<string>(name: "FNE_Ist_Stx52", type: "text", nullable: true),
                    FNEStx52Bemerkung = table.Column<string>(name: "FNE_Stx52_Bemerkung", type: "text", nullable: true),
                    FNEIstStx52b = table.Column<string>(name: "FNE_Ist_Stx52b", type: "text", nullable: true),
                    FNEStx52bBemerkung = table.Column<string>(name: "FNE_Stx52b_Bemerkung", type: "text", nullable: true),
                    FNEIstStx53 = table.Column<string>(name: "FNE_Ist_Stx53", type: "text", nullable: true),
                    FNEStx53Bemerkung = table.Column<string>(name: "FNE_Stx53_Bemerkung", type: "text", nullable: true),
                    FNEIstStx56 = table.Column<string>(name: "FNE_Ist_Stx56", type: "text", nullable: true),
                    FNEStx56Bemerkung = table.Column<string>(name: "FNE_Stx56_Bemerkung", type: "text", nullable: true),
                    FNEPlanStx56a = table.Column<string>(name: "FNE_Plan_Stx56a", type: "text", nullable: true),
                    FNEIstStx56a = table.Column<string>(name: "FNE_Ist_Stx56a", type: "text", nullable: true),
                    FNEStx56aBemerkung = table.Column<string>(name: "FNE_Stx56a_Bemerkung", type: "text", nullable: true),
                    FNEPlanStx59k = table.Column<string>(name: "FNE_Plan_Stx59k", type: "text", nullable: true),
                    FNEIstStx59k = table.Column<string>(name: "FNE_Ist_Stx59k", type: "text", nullable: true),
                    FNEStx59kBemerkung = table.Column<string>(name: "FNE_Stx59k_Bemerkung", type: "text", nullable: true),
                    FNEIstStx60 = table.Column<string>(name: "FNE_Ist_Stx60", type: "text", nullable: true),
                    FNEStx60Bemerkung = table.Column<string>(name: "FNE_Stx60_Bemerkung", type: "text", nullable: true),
                    FNEPlanStx63 = table.Column<string>(name: "FNE_Plan_Stx63", type: "text", nullable: true),
                    FNEIstStx63 = table.Column<string>(name: "FNE_Ist_Stx63", type: "text", nullable: true),
                    FNEStx63Bemerkung = table.Column<string>(name: "FNE_Stx63_Bemerkung", type: "text", nullable: true),
                    FNEPlanStx70 = table.Column<string>(name: "FNE_Plan_Stx70", type: "text", nullable: true),
                    FNEIstStx70 = table.Column<string>(name: "FNE_Ist_Stx70", type: "text", nullable: true),
                    FNEStx70Bemerkung = table.Column<string>(name: "FNE_Stx70_Bemerkung", type: "text", nullable: true),
                    FNESollStx71 = table.Column<string>(name: "FNE_Soll_Stx71", type: "text", nullable: true),
                    FNEPlanStx71 = table.Column<string>(name: "FNE_Plan_Stx71", type: "text", nullable: true),
                    FNEIstStx71 = table.Column<string>(name: "FNE_Ist_Stx71", type: "text", nullable: true),
                    FNEStx71Bemerkung = table.Column<string>(name: "FNE_Stx71_Bemerkung", type: "text", nullable: true),
                    FNEIstStx71a = table.Column<string>(name: "FNE_Ist_Stx71a", type: "text", nullable: true),
                    FNEStx71aBemerkung = table.Column<string>(name: "FNE_Stx71a_Bemerkung", type: "text", nullable: true),
                    FNESollStx90 = table.Column<string>(name: "FNE_Soll_Stx90", type: "text", nullable: true),
                    FNEPlanStx90 = table.Column<string>(name: "FNE_Plan_Stx90", type: "text", nullable: true),
                    FNEIstStx90 = table.Column<string>(name: "FNE_Ist_Stx90", type: "text", nullable: true),
                    FNEStx90Bemerkung = table.Column<string>(name: "FNE_Stx90_Bemerkung", type: "text", nullable: true),
                    FNEIstStx91 = table.Column<string>(name: "FNE_Ist_Stx91", type: "text", nullable: true),
                    FNEStx91Bemerkung = table.Column<string>(name: "FNE_Stx91_Bemerkung", type: "text", nullable: true),
                    NE33Projektart = table.Column<string>(name: "NE33_Projektart", type: "text", nullable: true),
                    NE33NENr = table.Column<string>(name: "NE33_NE_Nr", type: "text", nullable: true),
                    NE33ProjektNummer = table.Column<string>(name: "NE33_ProjektNummer", type: "text", nullable: true),
                    NE33Projektstand = table.Column<string>(name: "NE33_Projektstand", type: "text", nullable: true),
                    NE33IstStx30 = table.Column<string>(name: "NE33_Ist_Stx30", type: "text", nullable: true),
                    NE33SollStx71 = table.Column<string>(name: "NE33_Soll_Stx71", type: "text", nullable: true),
                    NE33PlanStx71 = table.Column<string>(name: "NE33_Plan_Stx71", type: "text", nullable: true),
                    NE33IstStx71 = table.Column<string>(name: "NE33_Ist_Stx71", type: "text", nullable: true),
                    NE33SollStx90 = table.Column<string>(name: "NE33_Soll_Stx90", type: "text", nullable: true),
                    NE33PlanStx90 = table.Column<string>(name: "NE33_Plan_Stx90", type: "text", nullable: true),
                    NE33IstStx90 = table.Column<string>(name: "NE33_Ist_Stx90", type: "text", nullable: true),
                    NE33IstStx91 = table.Column<string>(name: "NE33_Ist_Stx91", type: "text", nullable: true),
                    NE32Projektart = table.Column<string>(name: "NE32_Projektart", type: "text", nullable: true),
                    NE32NENr = table.Column<string>(name: "NE32_NE_Nr", type: "text", nullable: true),
                    NE32ProjektNummer = table.Column<string>(name: "NE32_ProjektNummer", type: "text", nullable: true),
                    NE32Projektstand = table.Column<string>(name: "NE32_Projektstand", type: "text", nullable: true),
                    NE32IstStx30 = table.Column<string>(name: "NE32_Ist_Stx30", type: "text", nullable: true),
                    NE32SollStx71 = table.Column<string>(name: "NE32_Soll_Stx71", type: "text", nullable: true),
                    NE32PlanStx71 = table.Column<string>(name: "NE32_Plan_Stx71", type: "text", nullable: true),
                    NE32IstStx71 = table.Column<string>(name: "NE32_Ist_Stx71", type: "text", nullable: true),
                    NE32SollStx90 = table.Column<string>(name: "NE32_Soll_Stx90", type: "text", nullable: true),
                    NE32PlanStx90 = table.Column<string>(name: "NE32_Plan_Stx90", type: "text", nullable: true),
                    NE32IstStx90 = table.Column<string>(name: "NE32_Ist_Stx90", type: "text", nullable: true),
                    NE32IstStx91 = table.Column<string>(name: "NE32_Ist_Stx91", type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RouterSwapAktuells", x => x.id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "RouterAktuell");

            migrationBuilder.DropTable(
                name: "RouterSwapAktuells");
        }
    }
}
