// <auto-generated />
using ExcelOperations.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExcelOperations.Migrations
{
    [DbContext(typeof(EntityDbContext))]
    [Migration("20230208114403_migv3")]
    partial class migv3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExcelOperations.DocEntity.RouterAktuell", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Alt")
                        .HasColumnType("text");

                    b.Property<string>("Anz_NE30")
                        .HasColumnType("text");

                    b.Property<string>("Anz_NE31")
                        .HasColumnType("text");

                    b.Property<string>("Anz_NE32")
                        .HasColumnType("text");

                    b.Property<string>("Anz_NE33")
                        .HasColumnType("text");

                    b.Property<string>("Bezeichnung")
                        .HasColumnType("text");

                    b.Property<string>("CtK_Status")
                        .HasColumnType("text");

                    b.Property<string>("DF")
                        .HasColumnType("text");

                    b.Property<string>("DF_1st_Stx90")
                        .HasColumnType("text");

                    b.Property<string>("DF_Ist")
                        .HasColumnType("text");

                    b.Property<string>("Demand")
                        .HasColumnType("text");

                    b.Property<string>("Dim_Beauftragungsform")
                        .HasColumnType("text");

                    b.Property<string>("Dim_OSPF")
                        .HasColumnType("text");

                    b.Property<string>("Dim_POC_Projekt")
                        .HasColumnType("text");

                    b.Property<string>("Dim_Squads")
                        .HasColumnType("text");

                    b.Property<string>("Eigentumer")
                        .HasColumnType("text");

                    b.Property<string>("Festnetzplaner")
                        .HasColumnType("text");

                    b.Property<string>("GU_Projekt")
                        .HasColumnType("text");

                    b.Property<string>("GU_Transport")
                        .HasColumnType("text");

                    b.Property<string>("Gebaudeart")
                        .HasColumnType("text");

                    b.Property<string>("Infrastruktur_Soll_Baseframe_Radio_MW")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx11")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx18b")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx29b")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx29t")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx29y")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx29z")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx30")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx30n")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx30o")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx30p")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx40")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx40Stern")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx43")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx43a")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx43c")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx44")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx51a")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx51b")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx51r")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx52b")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx52n")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx52p")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx53")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx59")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx59k")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx60")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx62a")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx62g")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx62j")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx62r")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx62w")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx68n")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx68o")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx68p")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx71")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx71a")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx71b")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx71c")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx80")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx87r")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx88i")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx89")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx90")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx91")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx91c")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx91r")
                        .HasColumnType("text");

                    b.Property<string>("Kol_NE78_MxMS")
                        .HasColumnType("text");

                    b.Property<string>("LL")
                        .HasColumnType("text");

                    b.Property<string>("LL_1st_Stx90")
                        .HasColumnType("text");

                    b.Property<string>("LL_Ist")
                        .HasColumnType("text");

                    b.Property<string>("MP_POC")
                        .HasColumnType("text");

                    b.Property<string>("MW")
                        .HasColumnType("text");

                    b.Property<string>("MW_1st_Stx90")
                        .HasColumnType("text");

                    b.Property<string>("MW_Ist")
                        .HasColumnType("text");

                    b.Property<string>("NE_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("NE_Name")
                        .HasColumnType("text");

                    b.Property<string>("NE_Nr")
                        .HasColumnType("text");

                    b.Property<string>("NE_Nr_EPlus")
                        .HasColumnType("text");

                    b.Property<string>("NRG_Transition")
                        .HasColumnType("text");

                    b.Property<string>("Ort")
                        .HasColumnType("text");

                    b.Property<string>("PLZ")
                        .HasColumnType("text");

                    b.Property<string>("POC_Projekt")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx40")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx59")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx59k")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx62g")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx62j")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx68n")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx68p")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx71")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx88i")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx90")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx91")
                        .HasColumnType("text");

                    b.Property<string>("Projekt_Equipment")
                        .HasColumnType("text");

                    b.Property<string>("Projekt_ID")
                        .HasColumnType("text");

                    b.Property<string>("Projektart")
                        .HasColumnType("text");

                    b.Property<string>("Projektbemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Projektstand")
                        .HasColumnType("text");

                    b.Property<string>("SAT")
                        .HasColumnType("text");

                    b.Property<string>("SAT_1st_Stx90")
                        .HasColumnType("text");

                    b.Property<string>("SAT_Ist")
                        .HasColumnType("text");

                    b.Property<string>("SONumber")
                        .HasColumnType("text");

                    b.Property<string>("SO_Nr_EPlus")
                        .HasColumnType("text");

                    b.Property<string>("SWD_POC_Sourcing")
                        .HasColumnType("text");

                    b.Property<string>("Soll_Stx62j")
                        .HasColumnType("text");

                    b.Property<string>("Soll_Stx71")
                        .HasColumnType("text");

                    b.Property<string>("Soll_Stx90")
                        .HasColumnType("text");

                    b.Property<string>("Strasse")
                        .HasColumnType("text");

                    b.Property<string>("Stx11_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx29t_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx29z_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx30_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx30n_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx30p_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx40_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx43a_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx44_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx51b_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx51r_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx52b_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx52n_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx52p_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx53_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx59_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx59k_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx60_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx62a_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx62g_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx62j_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx62w_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx68n_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx68p_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx71_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx71b_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx71c_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx80_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx88i_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx90_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx91_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("TOM_EXECUTION")
                        .HasColumnType("text");

                    b.Property<string>("TOM_PLANNING_PREPARATION")
                        .HasColumnType("text");

                    b.Property<string>("Template_Bezeichnung")
                        .HasColumnType("text");

                    b.Property<string>("UTS_Ticket_am_Projekt")
                        .HasColumnType("text");

                    b.Property<string>("Verantw_Organisationseinheit")
                        .HasColumnType("text");

                    b.Property<string>("WL")
                        .HasColumnType("text");

                    b.Property<string>("WL_1st_Stx90")
                        .HasColumnType("text");

                    b.Property<string>("WL_Ist")
                        .HasColumnType("text");

                    b.Property<string>("Ziel_des_Projekts")
                        .HasColumnType("text");

                    b.Property<string>("ZustandigeRegion")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("RouterAktuell");
                });

            modelBuilder.Entity("ExcelOperations.DocEntity.RouterSwapAktuell", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Alt")
                        .HasColumnType("text");

                    b.Property<string>("Anz_NE20")
                        .HasColumnType("text");

                    b.Property<string>("Anz_NE21")
                        .HasColumnType("text");

                    b.Property<string>("Anz_NE30")
                        .HasColumnType("text");

                    b.Property<string>("Anz_NE31")
                        .HasColumnType("text");

                    b.Property<string>("Anz_NE32")
                        .HasColumnType("text");

                    b.Property<string>("Anz_NE33")
                        .HasColumnType("text");

                    b.Property<string>("AuftragnehmerSystemtechnik")
                        .HasColumnType("text");

                    b.Property<string>("Bezeichnung")
                        .HasColumnType("text");

                    b.Property<string>("CRQ_GU")
                        .HasColumnType("text");

                    b.Property<string>("DF_Ist")
                        .HasColumnType("text");

                    b.Property<string>("DIM_ID")
                        .HasColumnType("text");

                    b.Property<string>("DIM_Status")
                        .HasColumnType("text");

                    b.Property<string>("DIM_zust_Abbauer")
                        .HasColumnType("text");

                    b.Property<string>("Demand")
                        .HasColumnType("text");

                    b.Property<string>("Dim_Beauftragungsform")
                        .HasColumnType("text");

                    b.Property<string>("Dim_SquadsMAC")
                        .HasColumnType("text");

                    b.Property<string>("Eigentumer")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Alt")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Demand")
                        .HasColumnType("text");

                    b.Property<string>("FNE_GU_Projekt")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Ist_Stx30")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Ist_Stx40Stern")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Ist_Stx43a")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Ist_Stx44")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Ist_Stx52")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Ist_Stx52b")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Ist_Stx53")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Ist_Stx56")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Ist_Stx56a")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Ist_Stx59k")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Ist_Stx60")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Ist_Stx63")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Ist_Stx70")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Ist_Stx71")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Ist_Stx71a")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Ist_Stx90")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Ist_Stx91")
                        .HasColumnType("text");

                    b.Property<string>("FNE_MP_POC")
                        .HasColumnType("text");

                    b.Property<string>("FNE_NE_Nr")
                        .HasColumnType("text");

                    b.Property<string>("FNE_POCProjekt")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Plan_Stx40Stern")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Plan_Stx56a")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Plan_Stx59k")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Plan_Stx63")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Plan_Stx70")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Plan_Stx71")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Plan_Stx90")
                        .HasColumnType("text");

                    b.Property<string>("FNE_ProjektID")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Projektart")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Projektbemerkung")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Projektbezeichnung")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Projektstand")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Soll_Stx71")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Soll_Stx90")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Stx30_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Stx40Stern_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Stx43a_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Stx44_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Stx52_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Stx52b_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Stx53_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Stx56_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Stx56a_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Stx59k_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Stx60_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Stx63_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Stx70_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Stx71_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Stx71a_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Stx90_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("FNE_Stx91_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("FNE_TemplateBezeichnung")
                        .HasColumnType("text");

                    b.Property<string>("FNE_VerantwOrg")
                        .HasColumnType("text");

                    b.Property<string>("Festnetzplaner")
                        .HasColumnType("text");

                    b.Property<string>("GU_Projekt")
                        .HasColumnType("text");

                    b.Property<string>("Gebaudeart")
                        .HasColumnType("text");

                    b.Property<string>("IM_ID")
                        .HasColumnType("text");

                    b.Property<string>("IM_Status")
                        .HasColumnType("text");

                    b.Property<string>("IM_gepl_Installation")
                        .HasColumnType("text");

                    b.Property<string>("IM_gepl_Lieferung")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx11")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx29z")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx30")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx30n")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx43a")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx44")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx48")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx50")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx51a")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx51b")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx51r")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx59")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx59k")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx60")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx62a")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx62g")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx62j")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx62r")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx62w")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx68n")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx70")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx71")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx71a")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx71b")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx71c")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx88i")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx90")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx91")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx91a")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx91c")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx91r")
                        .HasColumnType("text");

                    b.Property<string>("LL_Ist")
                        .HasColumnType("text");

                    b.Property<string>("Linda_Grundgerat")
                        .HasColumnType("text");

                    b.Property<string>("Linda_StatusLeitung")
                        .HasColumnType("text");

                    b.Property<string>("MP_POC")
                        .HasColumnType("text");

                    b.Property<string>("MW_Ist")
                        .HasColumnType("text");

                    b.Property<string>("NE32_Ist_Stx30")
                        .HasColumnType("text");

                    b.Property<string>("NE32_Ist_Stx71")
                        .HasColumnType("text");

                    b.Property<string>("NE32_Ist_Stx90")
                        .HasColumnType("text");

                    b.Property<string>("NE32_Ist_Stx91")
                        .HasColumnType("text");

                    b.Property<string>("NE32_NE_Nr")
                        .HasColumnType("text");

                    b.Property<string>("NE32_Plan_Stx71")
                        .HasColumnType("text");

                    b.Property<string>("NE32_Plan_Stx90")
                        .HasColumnType("text");

                    b.Property<string>("NE32_ProjektNummer")
                        .HasColumnType("text");

                    b.Property<string>("NE32_Projektart")
                        .HasColumnType("text");

                    b.Property<string>("NE32_Projektstand")
                        .HasColumnType("text");

                    b.Property<string>("NE32_Soll_Stx71")
                        .HasColumnType("text");

                    b.Property<string>("NE32_Soll_Stx90")
                        .HasColumnType("text");

                    b.Property<string>("NE33_Ist_Stx30")
                        .HasColumnType("text");

                    b.Property<string>("NE33_Ist_Stx71")
                        .HasColumnType("text");

                    b.Property<string>("NE33_Ist_Stx90")
                        .HasColumnType("text");

                    b.Property<string>("NE33_Ist_Stx91")
                        .HasColumnType("text");

                    b.Property<string>("NE33_NE_Nr")
                        .HasColumnType("text");

                    b.Property<string>("NE33_Plan_Stx71")
                        .HasColumnType("text");

                    b.Property<string>("NE33_Plan_Stx90")
                        .HasColumnType("text");

                    b.Property<string>("NE33_ProjektNummer")
                        .HasColumnType("text");

                    b.Property<string>("NE33_Projektart")
                        .HasColumnType("text");

                    b.Property<string>("NE33_Projektstand")
                        .HasColumnType("text");

                    b.Property<string>("NE33_Soll_Stx71")
                        .HasColumnType("text");

                    b.Property<string>("NE33_Soll_Stx90")
                        .HasColumnType("text");

                    b.Property<string>("NE_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("NE_Name")
                        .HasColumnType("text");

                    b.Property<string>("NE_Nr")
                        .HasColumnType("text");

                    b.Property<string>("Ort")
                        .HasColumnType("text");

                    b.Property<string>("PLZ")
                        .HasColumnType("text");

                    b.Property<string>("POCBEnde")
                        .HasColumnType("text");

                    b.Property<string>("POCProjekt")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx29z")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx48")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx51a")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx59")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx59k")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx62g")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx62j")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx68n")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx71")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx90")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx91")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx91a")
                        .HasColumnType("text");

                    b.Property<string>("ProjektID")
                        .HasColumnType("text");

                    b.Property<string>("Projektart")
                        .HasColumnType("text");

                    b.Property<string>("Projektbemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Projektstand")
                        .HasColumnType("text");

                    b.Property<string>("RLM")
                        .HasColumnType("text");

                    b.Property<string>("RSTP_Ist")
                        .HasColumnType("text");

                    b.Property<string>("Routeralt")
                        .HasColumnType("text");

                    b.Property<string>("Routerneu")
                        .HasColumnType("text");

                    b.Property<string>("SO_Nr")
                        .HasColumnType("text");

                    b.Property<string>("SO_Nr_EPlus")
                        .HasColumnType("text");

                    b.Property<string>("Soll_Stx48")
                        .HasColumnType("text");

                    b.Property<string>("Soll_Stx51a")
                        .HasColumnType("text");

                    b.Property<string>("Soll_Stx71")
                        .HasColumnType("text");

                    b.Property<string>("Soll_WL")
                        .HasColumnType("text");

                    b.Property<string>("StandortKlasse")
                        .HasColumnType("text");

                    b.Property<string>("Strabe")
                        .HasColumnType("text");

                    b.Property<string>("Stx11_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx29z_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx30_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx43a_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx44_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx51a_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx51b_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx51r_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx59_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx59k_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx60_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx62a_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx62g_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx62j_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx62w_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx68n_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx71_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx71a_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx71b_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx71c_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx88i_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx90_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx91_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx91a_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("TOM_EXECUTION")
                        .HasColumnType("text");

                    b.Property<string>("TOM_PLANNING_PREPARATION")
                        .HasColumnType("text");

                    b.Property<string>("TemplateBezeichnung")
                        .HasColumnType("text");

                    b.Property<string>("UGG")
                        .HasColumnType("text");

                    b.Property<string>("VerantwOrgeinheit")
                        .HasColumnType("text");

                    b.Property<string>("VerbindlicherJSLRouter")
                        .HasColumnType("text");

                    b.Property<string>("ZuständigeRegion")
                        .HasColumnType("text");

                    b.Property<string>("aktuell")
                        .HasColumnType("text");

                    b.Property<string>("dim_OSPFRulexakta")
                        .HasColumnType("text");

                    b.Property<string>("geplantesEnde")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("RouterSwapAktuells");
                });

            modelBuilder.Entity("ExcelOperations.DocEntity.XWDMAktuell", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Alt")
                        .HasColumnType("text");

                    b.Property<string>("Bezeichnung")
                        .HasColumnType("text");

                    b.Property<string>("BudgetDatum")
                        .HasColumnType("text");

                    b.Property<string>("CtK_Status")
                        .HasColumnType("text");

                    b.Property<string>("Demand")
                        .HasColumnType("text");

                    b.Property<string>("Dim_Beauftragungsform")
                        .HasColumnType("text");

                    b.Property<string>("Dim_OSPFRule")
                        .HasColumnType("text");

                    b.Property<string>("Dim_POCProjekt")
                        .HasColumnType("text");

                    b.Property<string>("Dim_Squads")
                        .HasColumnType("text");

                    b.Property<string>("Eigentümer")
                        .HasColumnType("text");

                    b.Property<string>("Equipment_Stern")
                        .HasColumnType("text");

                    b.Property<string>("Festnetzplaner")
                        .HasColumnType("text");

                    b.Property<string>("GU_Projekt")
                        .HasColumnType("text");

                    b.Property<string>("Gebäudeart")
                        .HasColumnType("text");

                    b.Property<string>("Infrastruktur_Soll_Baseframe_Radio_MW")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx11")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx29t")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx30")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx30n")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx30o")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx30p")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx40")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx40Stern")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx43")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx43a")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx43c")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx44")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx48")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx50")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx51a")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx51b")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx51l")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx51r")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx52b")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx52r")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx53")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx59")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx59k")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx60")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx62a")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx62g")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx62j")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx62r")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx62w")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx68n")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx68o")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx68p")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx71")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx71a")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx71b")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx71c")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx80")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx87r")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx88i")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx89")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx90")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx91")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx91a")
                        .HasColumnType("text");

                    b.Property<string>("Ist_Stx91r")
                        .HasColumnType("text");

                    b.Property<string>("KapazitatWDM")
                        .HasColumnType("text");

                    b.Property<string>("MP_POC")
                        .HasColumnType("text");

                    b.Property<string>("NE_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("NE_Equipment_Bestand")
                        .HasColumnType("text");

                    b.Property<string>("NE_Equipment_Ziel")
                        .HasColumnType("text");

                    b.Property<string>("NE_Name")
                        .HasColumnType("text");

                    b.Property<string>("NE_Nr")
                        .HasColumnType("text");

                    b.Property<string>("NE_Nr_EPlus")
                        .HasColumnType("text");

                    b.Property<string>("NRGTransition")
                        .HasColumnType("text");

                    b.Property<string>("Ort")
                        .HasColumnType("text");

                    b.Property<string>("PLZ")
                        .HasColumnType("text");

                    b.Property<string>("POC_Projekt")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx40")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx48")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx50")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx59k")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx60")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx62j")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx71")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx88i")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx90")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx91")
                        .HasColumnType("text");

                    b.Property<string>("Plan_Stx91a")
                        .HasColumnType("text");

                    b.Property<string>("ProjektID")
                        .HasColumnType("text");

                    b.Property<string>("Projekt_Equipment")
                        .HasColumnType("text");

                    b.Property<string>("Projektart")
                        .HasColumnType("text");

                    b.Property<string>("Projektbemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Projektstand")
                        .HasColumnType("text");

                    b.Property<string>("SO_Nr")
                        .HasColumnType("text");

                    b.Property<string>("SO_Nr_EPlus")
                        .HasColumnType("text");

                    b.Property<string>("Soll_Stx62j")
                        .HasColumnType("text");

                    b.Property<string>("Soll_Stx90")
                        .HasColumnType("text");

                    b.Property<string>("Straße")
                        .HasColumnType("text");

                    b.Property<string>("Stx11_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx29t_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx30_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx40_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx43a_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx44_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx48_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx50_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx51b_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx51l_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx52b_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx53_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx59_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx59k_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx60_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx62a_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx62j_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx62w_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx71_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx80_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx90_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx91_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("Stx91a_Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("TOM_EXECUTION")
                        .HasColumnType("text");

                    b.Property<string>("TOM_PLANNING_PREPARATION")
                        .HasColumnType("text");

                    b.Property<string>("TemplateBezeichnung")
                        .HasColumnType("text");

                    b.Property<string>("UTS_Ticket_am_Projekt")
                        .HasColumnType("text");

                    b.Property<string>("VerantwOrganisationseinheit")
                        .HasColumnType("text");

                    b.Property<string>("ZieldesProjekts")
                        .HasColumnType("text");

                    b.Property<string>("ZustandigeRegion")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("XWDMAktuells");
                });

            modelBuilder.Entity("ExcelOperations.DocEntity.ZugangsdatenAktuell", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Besonderheiten")
                        .HasColumnType("text");

                    b.Property<string>("COOPContract")
                        .HasColumnType("text");

                    b.Property<string>("COOPStatus")
                        .HasColumnType("text");

                    b.Property<string>("COOPTausch")
                        .HasColumnType("text");

                    b.Property<string>("DatumderSchliebung")
                        .HasColumnType("text");

                    b.Property<string>("Eigentümer")
                        .HasColumnType("text");

                    b.Property<string>("Equipment_SO")
                        .HasColumnType("text");

                    b.Property<string>("Gebäudeart")
                        .HasColumnType("text");

                    b.Property<string>("HochwertGK3")
                        .HasColumnType("text");

                    b.Property<string>("Infrastruktur_Soll_Baseframe_Radio_MW")
                        .HasColumnType("text");

                    b.Property<string>("Netzelement")
                        .HasColumnType("text");

                    b.Property<string>("NordlBreiteWGS84")
                        .HasColumnType("text");

                    b.Property<string>("Ort")
                        .HasColumnType("text");

                    b.Property<string>("OstlLangeWGS84")
                        .HasColumnType("text");

                    b.Property<string>("PLZ")
                        .HasColumnType("text");

                    b.Property<string>("Parkplätze")
                        .HasColumnType("text");

                    b.Property<string>("RechtswertGK3")
                        .HasColumnType("text");

                    b.Property<string>("SO_Nr")
                        .HasColumnType("text");

                    b.Property<string>("SO_Nr_EPlus")
                        .HasColumnType("text");

                    b.Property<string>("Schliebung")
                        .HasColumnType("text");

                    b.Property<string>("StandortdesTresors")
                        .HasColumnType("text");

                    b.Property<string>("Strabe")
                        .HasColumnType("text");

                    b.Property<string>("Umgebungspflege")
                        .HasColumnType("text");

                    b.Property<string>("Zufahrtsbeschreibung")
                        .HasColumnType("text");

                    b.Property<string>("Zugangsmöglichkeit")
                        .HasColumnType("text");

                    b.Property<string>("Zugangsregelung")
                        .HasColumnType("text");

                    b.Property<string>("ZustandigeRegion")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("ZugangsdatenAktuell");
                });
#pragma warning restore 612, 618
        }
    }
}
